
               TOKEN	              TYPE	    TOKEN CODE       line_number      POINTER VALUE

                void	          IDENTIFIER	      34	             0		           0
         newFunction	          IDENTIFIER	      34	             0		           5
                FILE	          IDENTIFIER	      34	             0		          17
                  fp	          IDENTIFIER	      34	             0		          23
                   {	         PUNCTUATION	      39	             1		           0
                 int	             KEYWORD	       0	             2		           1
                   a	          IDENTIFIER	      34	             2		           5
                   b	          IDENTIFIER	      34	             2		           7
                   c	          IDENTIFIER	      34	             2		           9
                   ,	         PUNCTUATION	      39	             2		           6
                   ;	         PUNCTUATION	      39	             2		          10
                char	             KEYWORD	       2	             3		           1
                  ch	          IDENTIFIER	      34	             3		           1
                 100	            CONSTANT	      33	             3		          10
                   =	          ASSIGNMENT	      37	             3		           9
                   ;	         PUNCTUATION	      39	             3		          13
              printf	          IDENTIFIER	      34	             5		           1
                   }	         PUNCTUATION	      39	             7		           0
                 int	             KEYWORD	       0	             8		           0
                main	          IDENTIFIER	      34	             8		           4
                   {	         PUNCTUATION	      39	             9		           0
                 int	             KEYWORD	       0	            10		           1
                   j	          IDENTIFIER	      34	            10		           5
                   0	            CONSTANT	      33	            10		           7
                   =	          ASSIGNMENT	      37	            10		           6
                   ;	         PUNCTUATION	      39	            10		           8
                char	             KEYWORD	       2	            11		           1
                  ch	          IDENTIFIER	      34	            11		           1
                   ;	         PUNCTUATION	      39	            11		           8
               while	             KEYWORD	      11	            12		           1
                   1	            CONSTANT	      33	            12		           7
                   {	         PUNCTUATION	      39	            13		           1
                  ch	          IDENTIFIER	      34	            14		           2
             getchar	          IDENTIFIER	      34	            14		           5
                   =	          ASSIGNMENT	      37	            14		           4
                   ;	         PUNCTUATION	      39	            14		          14
                  if	             KEYWORD	       9	            15		           2
                  ch	          IDENTIFIER	      34	            15		           5
                 EOF	          IDENTIFIER	      34	            15		           9
                  ==	         CONDITIONAL	      35	            15		           7
                   =	          ASSIGNMENT	      37	            15		           7
               break	             KEYWORD	       4	            16		           3
                   ;	         PUNCTUATION	      39	            16		           8
                  if	             KEYWORD	       9	            17		           2
                  ch	          IDENTIFIER	      34	            17		           5
                  ==	         CONDITIONAL	      35	            17		           7
                   =	          ASSIGNMENT	      37	            17		           7
                   {	         PUNCTUATION	      39	            18		           2
               while	             KEYWORD	      11	            19		           3
                  ch	          IDENTIFIER	      34	            19		          10
             getchar	          IDENTIFIER	      34	            19		          13
                  !=	         CONDITIONAL	      35	            19		          23
                   =	          ASSIGNMENT	      37	            19		          12
                   ;	         PUNCTUATION	      39	            20		           4
                   }	         PUNCTUATION	      39	            21		           2
                  if	             KEYWORD	       9	            23		           2
                  ch	          IDENTIFIER	      34	            23		           5
                  ==	         CONDITIONAL	      35	            23		           7
                   =	          ASSIGNMENT	      37	            23		           7
                   {	         PUNCTUATION	      39	            24		           2
                   i	          IDENTIFIER	      34	            25		           3
                   j	          IDENTIFIER	      34	            25		           7
                   0	            CONSTANT	      33	            25		           9
                   =	          ASSIGNMENT	      37	            25		           8
                  ++	 INCREMENT/DECREMENT	      38	            25		           4
                   ,	         PUNCTUATION	      39	            25		           6
                   ;	         PUNCTUATION	      39	            25		          10
                   }	         PUNCTUATION	      39	            26		           2
                else	             KEYWORD	      10	            27		           2
                   {	         PUNCTUATION	      39	            28		           2
               lines	          IDENTIFIER	      34	            29		           3
                   i	          IDENTIFIER	      34	            29		           4
                   j	          IDENTIFIER	      34	            29		          12
                  ch	          IDENTIFIER	      34	            29		          15
                   =	          ASSIGNMENT	      37	            29		          14
                   ;	         PUNCTUATION	      39	            29		          17
                   j	          IDENTIFIER	      34	            30		           3
                  ++	 INCREMENT/DECREMENT	      38	            30		           4
                   ;	         PUNCTUATION	      39	            30		           6
                   }	         PUNCTUATION	      39	            31		           2
                   }	         PUNCTUATION	      39	            32		           1
                   }	         PUNCTUATION	      39	            33		           0
                   }	         PUNCTUATION	      39	            35		           0
